version: '3.8'

services:
  app:
    build: .
    expose: 
      - 8003
    ports:
      - '8003:8081'
    command: "npm start"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
